Repository agnwinds/python, pull requests merged in 2018-08, with the labels that each got.

#402 corrected if statement in emission.c for photon directions
  source/emission.c
  source/matom.c
  source/python.h
Labels: belfast, bug, into_dev

#404 Multiple cleanups: rm CHOICE, rm SCATTER_MODE_ANISOTROPIC, streamline line transfer modes
  source/Makefile
  source/anisowind.c
  source/emission.c
  source/extract.c
  source/gridwind.c
  source/photo_gen_matom.c
  source/python.h
  source/resonate.c
  source/setup_domains.c
  source/templates.h
  source/trans_phot.c
  source/wind2d.c
Labels: Clean Up, belfast, into_dev

#411 Fixes/clean ups for various @bug tags and XXX comments, as documented…
  source/bb.c
  source/foo.h
  source/get_atomicdata.c
  source/ionization.c
  source/photon_gen.c
  source/pi_rates.c
  source/python.c
  source/reposition.c
  source/rtheta.c
  source/setup.c
  source/setup_domains.c
  source/templates.h
  source/trans_phot.c
Labels: belfast
