Repository agnwinds/python, pull requests merged in 2019-07, with the labels that each got.

#538 k-packet changes for free-free cooling
  source/matom.c
  source/matrix_ion.c
  source/para_update.c
  source/photo_gen_matom.c
  source/python.h
  source/run.c
  source/trans_phot.c
  source/wind2d.c
Labels: closed with caveat, into_dev, macro-atom

#547 Added license and citation files
  CITATION.cff
  LICENSE.md
Labels: admin

#550 Two changes: shorter GSL compilation for travis + error message to address bug #316
  .travis.yml
  Makefile.in
  source/setup_line_transfer.c
Labels: into_dev

#553 Fixed synonym bug
  source/atomic_proto.h
  source/log.h
  source/rdpar.c
  source/synonyms.c
  source/templates.h
Labels: bug

#554 Quick fix for synonyms
  source/synonyms.c
Labels: bug
