Repository agnwinds/python, pull requests merged in 2024-05, with the labels that each got.

#1074 Fix delay dump database creation from text
  py_progs/py4py/py4py/reverb/__init__.py
Labels: bug

#1070 Fix CITATION.cff file
  CITATION.cff
Labels: documentation

#1072 Updating `reverb.filter_line` documentation
  docs/sphinx/source/input/parameters/other/Reverb/Reverb.filter_line.rst
Labels: documentation

#1080 Update matom.c
  source/atomicdata.c
  source/matom.c
Labels: bug, atomic, macro-atom

#1029 attempt to fix translation issues in imported models
  .gitignore
  source/disk.c
  source/phot_util.c
  source/photon2d.c
  source/reverb.c
  source/roche.c
  source/templates.h
  source/tests/Makefile
  source/tests/tests/suites.h
  source/tests/tests/test_translate.c
  source/tests/unit_test_main.c
Labels: high
